---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**.js"
exclude_paths:
- coverage/
- doc/
- lib/
- node_modules/
- __tests__/
